basic/urls.py
"""sns_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns=[
    path('',showmain,name="index"),
    path('like',like, name = "like"),
    path('experience',experience, name = "experience"),
    path('<str:id>',detail, name = "detail"),
    path('new/',new, name = "new"),
    path('create/',create, name = "create"),
    path('edit/<str:id>', edit, name="edit"),
    path('posts/', posts, name="posts"),
    path('update/<str:id>',update,name = "update"),
    path('delete/<str:id>',delete,name = "delete"),

]

main/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/",blank = True, null = True)


    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.utils import timezone

# Create your views here.

def showmain(request):
    return render(request, 'main/index.html')

def posts(request):
    posts = Post.objects.all()
    return render(request, 'main/posts.html', {'posts': posts})


def like(request):
    return render(request,'main/like.html')


def experience(request):
    return render(request,'main/experience.html')

def detail(request,id):
    post = get_object_or_404(Post, pk =id)
    return render(request,'main/detail.html', {'post' : post})

def new(request):
    return render(request,'main/new.html')

def create(request):
    new_post= Post()
    new_post.title = request.POST['title']
    new_post.writer = request.POST['writer']
    new_post.pub_date = timezone.now()
    new_post.image = request.FILES.get('image')
    new_post.body = request.POST['body']
    new_post.save()
    return redirect('main:detail', new_post.id)

def edit(request, id) : 
    edit_post = Post.objects.get(id=id)
    return render(request, 'main/edit.html',{'post':edit_post})


def update(request, id): 
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST['title']
    update_post.writer = request.POST['writer']
    update_post.pub_date = timezone.now()
    update_post.image = request.FILES.get('image')
    update_post.body = request.POST['body']
    update_post.save()
    return redirect('main:detail', update_post.id)


def delete(request, id):
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect('main:posts')

basic/templates/base.html
{% load static %}
<html lang = "ko">
    <head>
      
        <link rel = "stylesheet" href="{% static 'css/style.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Kiwi+Maru&family=Pacifico&family=Spinnaker&family=Coda:wght@800&family=Stylish&family=Poor+Story&display=swap" rel="stylesheet">
        <script
        src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
        <!-- 합쳐지고 최소화된 최신 CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

        <!-- 부가적인 테마 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

        <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
        <meta charset = "utf-8">
        <title> Yaena Lee</title>
         
    </head>

    <body>
      
        {%include 'shared/navbar.html'%}
        

            <div class = "title">
              <br>
              <h1 id = "name1">Yae Na Lee </h1>
            
              <h5 id = "lion">  member of like_lion Dongguk</h5>
              <br>
            </div>
        
        <div class = "container">
            {% block content %}
    
            {% endblock %}
        </div>
    </body>

    </html>

basic/templates/shared/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'main:index' %}">Profile <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'main:experience' %}">Experience</a>
      <a class="nav-item nav-link" href="{% url 'main:like' %}">What I like</a>
      <a class="nav-item nav-link" href="{% url 'main:posts' %}">Posts</a>
    </div>
  </div>
</nav>

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>{{post.title}}</h1>
작성자 : {{post.writer}}
날짜 : {{post.pub_date}}
<hr>
{% if post.image %}
    <p><img src = "{{ post.image.url }}" alt = "사진"></p>
{% endif %}
<p>{{post.body}}</p>
<a href="{%url 'main:edit' post.id%}">수정하기</a>
<a href = "{% url 'main:delete' post.id %}">삭제하기 </a>
{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %} 

{% block content %} 
<div class = "container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' post.id %}" method="post">
        {%csrf_token%} 
        <p>제목 : <input type="text" name="title" value = "{{post.title}}"></p>
        <p>작성자 : <input type="text" name="writer" value = "{{post.writer}}"></p>
        <p>사진 : <input type = "file" name = "image" value ="{{post.image}}"}}></p>
        <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
		<button type="submit">제출</button>
    </form>

</div>

{% endblock %}

main/templates/main/experience.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




  <br>
  <ul class="nav nav-pills" id = "index">
    <li role="presentation" ><a href="{% url 'main:index' %}">Profile</a></li>
    <li role="presentation" class="active"><a href="{% url 'main:experience' %}">Experience</a></li>
    <li role="presentation"><a href="{% url 'main:like' %}">What I like</a></li>
    <li role="presentation"><a href="{% url 'main:posts' %}">Post</a></li>
  </ul>



  <img id = img2 src = "{%static 'img/KakaoTalk_20210311_144314107_02.jpg' %}" width="500px" height="500px" />
  <style>
      h3{font-family: 'Poor Story', cursive ; color : orange; font-size : 30px; font-style:bold;}
    </style>
    <div class = info>
      <h3> 자격증 </h3>
      <ul class = information>
        <li > ADSP 빅데이터 준전문가 </li>
        <li> 사회조사분석사 2급</li>
        <li> 컴활1급</li>
        <li> GTQ 포토샵</li>
        <li> DELF B1</li>

      </ul>

      <h3> 활동내역 </h3>
      <ul class = information>
        <li > ​경영정보학과 35대 학생회 </li>
        <li> 코딩월드뉴스 에디터 2기</li>
        <li> 네이버 커넥트재단 CS50 코칭스터디 2기</li>
        <li>DB 대학생 기업경영스쿨 수료</li>
        <li> 멋사 9기 ( 활동중 ) </li>

      </ul>
  </div>

<br>

{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




  <br>
    <ul class="nav nav-pills" id = "index">
      <li role="presentation" class="active"><a href="{% url 'main:index' %}">Profile</a></li>
      <li role="presentation"><a href="{% url 'main:experience' %}">Experience</a></li>
      <li role="presentation"><a href="{% url 'main:like' %}">What I like</a></li>
      <li role="presentation"><a href="{% url 'main:posts' %}">Post</a></li>
    </ul>

  <br>

  <br>
  <img id=img1 src = "{%static 'img/KakaoTalk_20210311_121920336.jpg' %}" height=500px width=500px  />

  
  <style>
    h3{font-family: 'Spinnaker', sans-serif ; color : orange; font-size : 30px;}
  </style>

      <div class = info>
      <h3> Information </h3>
      <ul class = information>
        <li > 이름 : 이예나 </li>
        <li> 나이 : 23살 </li>
        <li> 학교 : 동국대학교 </li>

      </ul>
  
      <h3> Major </h3>
      <ul class = information>
        <li > 주전공 : Management Information System (경영정보학과)</li>
        <li> 연계전공 : Integrated Software (융합소프트웨어학과)</li>


      </ul>
      
      <h3> Future Dream</h3>
      <ul class = information>
        <li > 개발자 </li>
      
      
      
      </div>

      
      


{% endblock %}

main/templates/main/like.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <br>
  <ul class="nav nav-pills" id = "index">
    <li role="presentation" ><a href="{% url 'main:index' %}">Profile</a></li>
    <li role="presentation" ><a href="{% url 'main:experience' %}">Experience</a></li>
    <li role="presentation" class="active"><a href="{% url 'main:like' %}">What I like</a></li>
    <li role="presentation"><a href="{% url 'main:posts' %}">Post</a></li>
  </ul>

  <style>
      h3{font-family: 'Spinnaker', sans-serif ; color : orange; font-size : 30px;}
    </style>
  <h3>Coding</h3>
  <br>
  <h3> Taking Photos</h3>
  <img src = "{%static 'img/캡쳐.jpg' %}"/>
  <h3> Drawing </h3>
  <img src = "{%static 'img/KakaoTalk_20210406_041609108.jpg' %}" height = "80%" width="80%"/>
  <br> <br>

  


{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 




<form action ="{%url 'main:create'%}" method="post" enctype = "multipart/form-data">

    {%csrf_token%}
    <p>제목 : <input type = "text" name = "title"></p>
    <p>작성자 : <input type = "text" name = "writer"></p>
    <p>사진 : <input type = "file" name = "image"></p>
    <p>내용 : <textarea type = "text" name = "body" id = "" cols = "30" rows = "10"></textarea></p>
    <button type = "submit">제출</button>

</form>
{% endblock %}

main/templates/main/posts.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<br>
<ul class="nav nav-pills" id = "index">
  <li role="presentation" ><a href="{% url 'main:index' %}">Profile</a></li>
  <li role="presentation" ><a href="{% url 'main:experience' %}">Experience</a></li>
  <li role="presentation"><a href="{% url 'main:like' %}">What I like</a></li>
  <li role="presentation" class="active"><a href="{% url 'main:posts' %}">Post</a></li>
</ul>




    <h1>글 목록</h1>
    
    <div>
        {% for post in posts %}
        <div>
          <h3>{{post.title}}</h3><br>
          {{post.writer}}<br>
          {{post.summary}}<br>
          <a href = "{%url 'main:detail' post.id %}">..자세히</a><hr>
        </div>
        {%endfor%}  
      </div>

      <h3><a href="{%url 'main:new'%}">글쓰기</a></h3>

{% endblock %}